# VEDA AI & ML Track – Task 8
## Simple Data Filtering

### Objective
Create a collection of student records and filter students based on marks, age, and department.

### Tools
- Python
- Jupyter Notebook
- Pandas

# Student records

students = [
    {"name": "Divakar", "age": 20, "department": "ECE", "marks": 88},
    {"name": "Harini", "age": 21, "department": "CSE", "marks": 92},
    {"name": "Keerthana", "age": 20, "department": "ECE", "marks": 76},
    {"name": "Dharaneesh", "age": 22, "department": "EEE", "marks": 85},
    {"name": "Arun", "age": 19, "department": "CSE", "marks": 68},
    {"name": "Priya", "age": 21, "department": "ECE", "marks": 95}
]

# Display all student records
for student in students:
    print(student)

## 1. Filter Students Based on Marks

Find students who scored 85 or above.

In [2]:
# Filter students with marks >= 85

high_scorers = []

for student in students:
    if student["marks"] >= 85:
        high_scorers.append(student)

print("Students with marks >= 85:")

for student in high_scorers:
    print(student)

Students with marks >= 85:
{'name': 'Divakar', 'age': 20, 'department': 'ECE', 'marks': 88}
{'name': 'Harini', 'age': 21, 'department': 'CSE', 'marks': 92}
{'name': 'Dharaneesh', 'age': 22, 'department': 'EEE', 'marks': 85}
{'name': 'Priya', 'age': 21, 'department': 'ECE', 'marks': 95}

## 2. Filter Students Based on Age

Find students who are 20 years old or younger.

In [5]:
# Filter students with age <= 20

young_students = []

for student in students:
    if student["age"] <= 20:
        young_students.append(student)

print("Students aged 20 or below:")

for student in young_students:
    print(student)

Students aged 20 or below:
{'name': 'Divakar', 'age': 20, 'department': 'ECE', 'marks': 88}
{'name': 'Keerthana', 'age': 20, 'department': 'ECE', 'marks': 76}
{'name': 'Arun', 'age': 19, 'department': 'CSE', 'marks': 68}

## 3. Filter Students Based on Department

Find all students belonging to the ECE department.

# Filter ECE students

ece_students = []

for student in students:
    if student["department"] == "ECE":
        ece_students.append(student)

print("ECE Students:")

for student in ece_students:
    print(student)

## 4. Multiple Filtering Conditions

Find ECE students who scored 80 or above.

In [7]:
# Filter ECE students with marks >= 80

filtered_students = []

for student in students:
    if student["department"] == "ECE" and student["marks"] >= 80:
        filtered_students.append(student)

print("ECE students with marks >= 80:")

for student in filtered_students:
    print(student)

ECE students with marks >= 80:
{'name': 'Divakar', 'age': 20, 'department': 'ECE', 'marks': 88}
{'name': 'Priya', 'age': 21, 'department': 'ECE', 'marks': 95}

## 5. Convert Student Records into a Pandas DataFrame

In [8]:
import pandas as pd

# Convert list of dictionaries into DataFrame
df = pd.DataFrame(students)

# Display DataFrame
df

         name  age department  marks
0     Divakar   20        ECE     88
1      Harini   21        CSE     92
2   Keerthana   20        ECE     76
3  Dharaneesh   22        EEE     85
4        Arun   19        CSE     68
5       Priya   21        ECE     95

## 6. Pandas Filtering Based on Marks

Display students who scored 85 or above.

In [9]:
df[df["marks"] >= 85]

         name  age department  marks
0     Divakar   20        ECE     88
1      Harini   21        CSE     92
3  Dharaneesh   22        EEE     85
5       Priya   21        ECE     95

## 7. Pandas Filtering Based on Department

Display students from the ECE department.

In [10]:
df[df["department"] == "ECE"]

        name  age department  marks
0    Divakar   20        ECE     88
2  Keerthana   20        ECE     76
5      Priya   21        ECE     95

## 8. Pandas Filtering Using Multiple Conditions

Display ECE students who scored 80 or above.

In [11]:
df[(df["department"] == "ECE") & (df["marks"] >= 80)]

      name  age department  marks
0  Divakar   20        ECE     88
5    Priya   21        ECE     95

## 9. Filtering Based on Age and Marks

Find students who are 20 years old or younger and scored 80 or above.

In [12]:
df[(df["age"] <= 20) & (df["marks"] >= 80)]

      name  age department  marks
0  Divakar   20        ECE     88

## 10. Filtering Using OR Condition

Find students who belong to either ECE or CSE.

In [13]:
df[
    (df["department"] == "ECE") |
    (df["department"] == "CSE")
]

        name  age department  marks
0    Divakar   20        ECE     88
1     Harini   21        CSE     92
2  Keerthana   20        ECE     76
4       Arun   19        CSE     68
5      Priya   21        ECE     95

## 11. Filtering and Sorting

Filter students who scored 80 or above and sort them by marks in descending order.

In [14]:
filtered_sorted = df[df["marks"] >= 80].sort_values(
    "marks",
    ascending=False
)

filtered_sorted

         name  age department  marks
5       Priya   21        ECE     95
1      Harini   21        CSE     92
0     Divakar   20        ECE     88
3  Dharaneesh   22        EEE     85

## 12. Final Filtered Student Output

Display ECE students who scored at least 80 marks.

In [15]:
final_result = df[
    (df["department"] == "ECE") &
    (df["marks"] >= 80)
]

print("Final filtered students:")

final_result

Final filtered students:

      name  age department  marks
0  Divakar   20        ECE     88
5    Priya   21        ECE     95

# Interview Questions

## 1. What is data filtering?

Data filtering is the process of selecting only the records that satisfy one or more specified conditions.

For example, we can filter students whose marks are greater than or equal to 85.

## 2. How would you filter a Pandas DataFrame?

A Pandas DataFrame can be filtered using Boolean conditions.

For example:

`df[df["marks"] >= 85]`

For multiple conditions, `&` is used for AND and `|` is used for OR.

Example:

`df[(df["department"] == "ECE") & (df["marks"] >= 80)]`

## 3. What is the difference between filtering and sorting?

Filtering selects rows that satisfy a particular condition.

Sorting changes the order of rows based on the values in one or more columns.

Example of filtering:

`df[df["marks"] >= 85]`

Example of sorting:

`df.sort_values("marks", ascending=False)`

Therefore:

- Filtering → selects specific records.
- Sorting → rearranges the order of records.

# Conclusion

In this task, student records were created using Python dictionaries.

The records were filtered based on:

- Marks
- Age
- Department
- Multiple conditions

Pandas was also used to convert the student records into a DataFrame and perform filtering operations efficiently.

This task helped demonstrate how conditional statements and Boolean conditions can be used to filter structured data.